export const GET_TIMESHEETS_PENDING = 'GET_TIMESHEETS_PENDING';
export const GET_TIMESHEETS_ERROR = 'GET_TIMESHEETS_ERROR';
export const GET_TIMESHEETS_SUCCESS = 'GET_TIMESHEETS_SUCCESS';

export const GET_DELETED_TIMESHEETS_PENDING = 'GET_DELETED_TIMESHEETS_PENDING';
export const GET_DELETED_TIMESHEETS_ERROR = 'GET_DELETED_TIMESHEETS_ERROR';
export const GET_DELETED_TIMESHEETS_SUCCESS = 'GET_DELETED_TIMESHEETS_SUCCESS';

export const CREATE_TIMESHEET_PENDING = 'CREATE_TIMESHEET_PENDING';
export const CREATE_TIMESHEET_ERROR = 'CREATE_TIMESHEET_ERROR';
export const CREATE_TIMESHEET_SUCCESS = 'CREATE_TIMESHEET_SUCCESS';

export const PUT_TIMESHEET_PENDING = 'PUT_TIMESHEET_PENDING';
export const PUT_TIMESHEET_ERROR = 'PUT_TIMESHEET_ERROR';
export const PUT_TIMESHEET_SUCCESS = 'PUT_TIMESHEET_SUCCESS';

export const DELETE_TIMESHEET_PENDING = 'DELETE_TIMESHEET_PENDING';
export const DELETE_TIMESHEET_ERROR = 'DELETE_TIMESHEET_ERROR';
export const DELETE_TIMESHEET_SUCCESS = 'DELETE_TIMESHEET_SUCCESS';
