export const GET_ALL_TIMESHEETS_PENDING = 'GET_ALL_TIMESHEETS_PENDING';
export const GET_ALL_TIMESHEETS_ERROR = 'GET_ALL_TIMESHEETS_ERROR';
export const GET_ALL_TIMESHEETS_SUCCESS = 'GET_ALL_TIMESHEETS_SUCCESS';
