export const GET_EMPLOYEES_PENDING = 'GET_EMPLOYEES_PENDING';
export const GET_EMPLOYEES_SUCCESS = 'GET_EMPLOYEES_SUCCESS';
export const GET_EMPLOYEES_ERROR = 'GET_EMPLOYEES_ERROR';

export const CREATE_EMPLOYEES_SUCCESS = 'CREATE_EMPLOYEES_SUCCESS';
export const CREATE_EMPLOYEES_ERROR = 'CREATE_EMPLOYEES_ERROR';
export const CREATE_EMPLOYEES_PENDING = 'CREATE_EMPLOYEES_PENDING';

export const UPDATE_EMPLOYEES_SUCCESS = 'CREATE_EMPLOYEES_SUCCESS';
export const UPDATE_EMPLOYEES_ERROR = 'CREATE_EMPLOYEES_ERROR';
export const UPDATE_EMPLOYEES_PENDING = 'CREATE_EMPLOYEES_PENDING';

export const DELETE_EMPLOYEES_SUCCESS = 'DELETE_EMPLOYEES_SUCCESS';
export const DELETE_EMPLOYEES_ERROR = 'DELETE_EMPLOYEES_ERROR';
export const DELETE_EMPLOYEES_PENDING = 'DELETE_EMPLOYEES_PENDING';
