export const GET_PROJECT_BY_ID_PENDING = 'GET_PROJECT_BY_ID_PENDING';
export const GET_PROJECT_BY_ID_SUCCESS = 'GET_PROJECT_BY_ID_SUCCESS';
export const GET_PROJECT_BY_ID_ERROR = 'GET_PROJECT_BY_ID_ERROR';
export const SET_LOADING_FALSE = 'SET_LOADING_FALSE';
