export const GET_PROJECT_BY_ID_PENDING = 'GET_PROJECT_BY_ID_PENDING';
export const GET_PROJECT_BY_ID_SUCCESS = 'GET_PROJECT_BY_ID_SUCCESS';
export const GET_PROJECT_BY_ID_ERROR = 'GET_PROJECT_BY_ID_ERROR';
