export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CLEAN_ERROR = 'CLEAN_ERROR';
export const SET_AUTHENTICATION = 'SET_AUTHENTICATION';
export const GET_ME_PENDING = 'GET_ME_PENDING';
export const GET_ME_SUCCESS = 'GET_ME_SUCCESS';
export const GET_ME_ERROR = 'GET_ME_ERROR';
